import fs from "node:fs";
import path from "node:path";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getAllMeta, getEntry } from "@/lib/content";
import { LabDetail } from "@/components/LabDetail";

interface PageProps {
  // Next 15+: route params arrive as a Promise that must be awaited.
  params: Promise<{ slug: string }>;
}

/** Prebuild a page per lab item at build time → fully static, indexable. */
export function generateStaticParams() {
  return getAllMeta("lab").map((p) => ({ slug: p.slug }));
}

/**
 * Per-item metadata. OG image source: `/og/lab/<slug>.png` (1200×630),
 * pre-generated by `scripts/generate-lab-og.mjs` from the hero clip's poster
 * with corner-sampled padding (the poster-based sibling of the essay text
 * cards). Namespaced under `og/lab/` so lab slugs can't collide with the
 * case-study OGs at `og/<slug>.png`. Existence-checked rather than assumed —
 * a lab item without a regen run falls back to the site default from the root
 * layout instead of linking a broken share card. Rerun the script when a
 * poster changes / a new lab item lands.
 */
const OG_W = 1200;
const OG_H = 630;

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const meta = getAllMeta("lab").find((p) => p.slug === slug);
  if (!meta) return {};
  const url = `/lab/${slug}`;
  const ogPath = `/og/lab/${slug}.png`;
  const ogExists = fs.existsSync(
    path.join(process.cwd(), "public", "og", "lab", `${slug}.png`),
  );
  const images = ogExists
    ? [{ url: ogPath, width: OG_W, height: OG_H, alt: meta.title }]
    : undefined;
  return {
    title: meta.title,
    description: meta.summary,
    openGraph: {
      type: "article",
      title: meta.title,
      description: meta.summary,
      url,
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: meta.title,
      description: meta.summary,
      images: ogExists ? [ogPath] : undefined,
    },
    alternates: { canonical: url },
  };
}

export default async function LabItemPage({ params }: PageProps) {
  const { slug } = await params;
  const exists = getAllMeta("lab").some((p) => p.slug === slug);
  if (!exists) notFound();
  const { meta, body } = getEntry("lab", slug);
  return <LabDetail meta={meta} body={body} />;
}
