import fs from "node:fs";
import path from "node:path";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getAllMeta } from "@/lib/content";
import { ProjectsSection } from "@/components/ProjectsSection";

interface PageProps {
  // Next 15+: route params arrive as a Promise that must be awaited.
  params: Promise<{ slug: string }>;
}

/** Prebuild a page per case study at build time → fully static, indexable. */
export function generateStaticParams() {
  return getAllMeta("work").map((p) => ({ slug: p.slug }));
}

/**
 * Per-case-study metadata — the whole reason this route exists. Each slug's
 * cover becomes its OG/Twitter share image, frontmatter drives title +
 * description.
 *
 * OG image source: `/og/<slug>.png` (1200×630), pre-generated by
 * `scripts/generate-case-og.mjs` from the cover with corner-sampled padding
 * — preserves the cover at the OG aspect without center-cropping. Rerun the
 * script when a cover changes. If a slug has no `/og/<slug>.png` yet, no
 * per-route image is set and the share preview falls back to the site
 * default from the root layout.
 */
const OG_W = 1200;
const OG_H = 630;

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const meta = getAllMeta("work").find((p) => p.slug === slug);
  if (!meta) return {};

  const url = `/design/${slug}`;
  const ogPath = `/og/${slug}.png`;
  // Existence-check the generated OG image rather than trusting it's there —
  // a freshly-added case study without a regen run shouldn't silently link a
  // broken share card. Falls back to the site default in that case.
  const ogExists = fs.existsSync(
    path.join(process.cwd(), "public", "og", `${slug}.png`),
  );
  const images = ogExists
    ? [{ url: ogPath, width: OG_W, height: OG_H, alt: meta.title }]
    : undefined;

  return {
    title: meta.title,
    description: meta.summary,
    openGraph: {
      type: "article",
      title: meta.title,
      description: meta.summary,
      url,
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: meta.title,
      description: meta.summary,
      images: ogExists ? [ogPath] : undefined,
    },
    alternates: { canonical: url },
  };
}

/**
 * Case-study route. Renders the same `ProjectsSection` as the home page,
 * but with `initialSlug` set so the explorer opens directly to the detail
 * view. The shared `(site)/layout.tsx` keeps the nav panel mounted across
 * navigation between `/` ↔ `/design/<slug>`, so visually this reads as the
 * grid being swapped for the detail — same in-place feel as the old hash
 * model, but with real URLs underneath.
 */
export default async function CaseStudyPage({ params }: PageProps) {
  const { slug } = await params;
  const exists = getAllMeta("work").some((p) => p.slug === slug);
  if (!exists) notFound();
  return <ProjectsSection initialSlug={slug} />;
}
